# Generated by Django 5.2.7 on 2025-11-07 22:42

import cloudinary_storage.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTypeTaskModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='writing_exam_images/')),
                ('task', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=30)),
                ('exam_type', models.CharField(choices=[('Academic', 'Academic'), ('General', 'General')], max_length=30)),
            ],
        ),
    ]
