# Generated by Django 5.2.7 on 2025-12-02 22:12

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTypeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_type', models.CharField(choices=[('Academic', 'Academic'), ('General', 'General')], default='Academic', max_length=50)),
                ('writing_task', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], default='task1', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Required for Task 1 (upload an image).', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='writing_images/')),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
