# Generated by Django 5.2.7 on 2025-11-11 21:16

import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTypeTaskModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=600, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='writing_exam_images/')),
                ('task', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=30)),
                ('exam_type', models.CharField(choices=[('Academic', 'Academic'), ('General', 'General')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WritingAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1_answer', models.TextField()),
                ('task2_answer', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_writing_answers', to=settings.AUTH_USER_MODEL)),
                ('type_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_answers', to='writing.writingtypetaskmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WritingEvaluationModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('task_response_task1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('coherence_cohesion_task1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('lexical_resource_task1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('grammatical_range_accuracy_task1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('overall_band_task1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('task_response_task2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('coherence_cohesion_task2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('lexical_resource_task2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('grammatical_range_accuracy_task2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('overall_band_task2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('areas_for_improvement', models.JSONField(blank=True, default=list)),
                ('total_overall_band', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('writing_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_evaluation', to='writing.writinganswermodel')),
            ],
        ),
    ]
