# Generated by Django 5.2.7 on 2025-12-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingevaluation',
            name='areas_for_improvement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingevaluation',
            name='strengths',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
