# Generated by Django 5.2.7 on 2025-11-08 00:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtypetaskmodel',
            name='image',
            field=models.ImageField(blank=True, max_length=600, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='writing_exam_images/'),
        ),
    ]
