# Generated by Django 5.2.7 on 2025-12-02 22:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtypetask',
            name='image',
            field=models.ImageField(blank=True, help_text='Required for Task 1 (upload an image).', max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='writing_images/'),
        ),
    ]
