# Generated by Django 5.2.7 on 2025-11-15 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_writingpracticesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='writinganswermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writinganswermodel',
            name='duration_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='writinganswermodel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
