# Generated by Django 5.2.7 on 2025-12-03 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writingpracticesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingpracticesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
