# Generated by Django 5.2.7 on 2025-11-15 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writinganswermodel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writinganswermodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='writinganswermodel',
            name='duration_time',
        ),
        migrations.RemoveField(
            model_name='writinganswermodel',
            name='start_time',
        ),
        migrations.CreateModel(
            name='LockExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_time', models.IntegerField(default=60)),
                ('locked_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_sessions', to='writing.writingtypetaskmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
