# Generated by Django 5.2.7 on 2025-11-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_remove_writinganswermodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockexamsession',
            name='locked_task',
        ),
        migrations.AddField(
            model_name='lockexamsession',
            name='locked_tasks',
            field=models.ManyToManyField(related_name='locked_sessions', to='writing.writingtypetaskmodel'),
        ),
    ]
