# Generated by Django 5.2.7 on 2025-12-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_alter_writingpracticesession_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1', models.TextField(blank=True, default='')),
                ('task2', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task1_type', models.ForeignKey(blank=True, help_text="Should reference a WritingTypeTask with writing_task='task1'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task1_answers', to='writing.writingtypetask')),
                ('task2_type', models.ForeignKey(blank=True, help_text="Should reference a WritingTypeTask with writing_task='task2'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task2_answers', to='writing.writingtypetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='writing_wri_user_id_ba8a05_idx')],
            },
        ),
    ]
