# Generated by Django 5.2.7 on 2025-12-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_writinganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='writinganswer',
            name='session',
            field=models.OneToOneField(blank=True, help_text='Without a linked active session this will not  be evaluated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.writingpracticesession'),
        ),
    ]
