# Generated by Django 5.2.7 on 2025-12-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_writinganswer_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_achievement_score_task1', models.FloatField(blank=True, null=True)),
                ('coherence_cohesion_score_task1', models.FloatField(blank=True, null=True)),
                ('lexical_resource_score_task1', models.FloatField(blank=True, null=True)),
                ('grammatical_range_accuracy_score_task1', models.FloatField(blank=True, null=True)),
                ('overall_band_score_task1', models.FloatField(blank=True, null=True)),
                ('task_achievement_score_task2', models.FloatField(blank=True, null=True)),
                ('coherence_cohesion_score_task2', models.FloatField(blank=True, null=True)),
                ('lexical_resource_score_task2', models.FloatField(blank=True, null=True)),
                ('grammatical_range_accuracy_score_task2', models.FloatField(blank=True, null=True)),
                ('overall_band_score_task2', models.FloatField(blank=True, null=True)),
                ('overall_writing_band', models.FloatField(blank=True, null=True)),
                ('writing_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='writing.writinganswer')),
            ],
        ),
    ]
