# Generated by Django 5.2.7 on 2025-12-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], default='academic', max_length=50)),
                ('total_passages', models.PositiveIntegerField(default=3)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(unique=True)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestionRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text="e.g., 'Questions 1-5', 'Questions A-C'", max_length=255, null=True)),
                ('serial_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMcqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reading/options/')),
                ('is_correct', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='reading.readingmcq')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('pre_note', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='PassagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('part_type', models.CharField(help_text="e.g., '1', 'A', 'None' ", max_length=2)),
                ('passage_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingpassage')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, help_text='section no. like Section 1, Section 2 etc.', max_length=255, null=True)),
                ('pre_passage_guide', models.TextField(blank=True, help_text="Instructions or guide before the passage. like 'Read the passage and answer the questions below.'", null=True)),
                ('passage', models.JSONField(default=dict, help_text="{ 'headline': 'the passage', 'part': '1/A/None', 'content': 'passage text' }")),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingexammodel')),
            ],
        ),
        migrations.AddField(
            model_name='readingmcq',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingquestionrange'),
        ),
    ]
