# Generated by Django 5.2.7 on 2025-12-05 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], default='academic', max_length=50)),
                ('total_passages', models.PositiveIntegerField(default=3)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, help_text='section no. like Section 1, Section 2 etc.', max_length=255, null=True)),
                ('pre_passage_guide', models.TextField(blank=True, help_text="Instructions or guide before the passage. like 'Read the passage and answer the questions below.'", null=True)),
                ('passage', models.JSONField(default=dict, help_text="{ 'headline': 'the passage', 'part': 1/A/None, 'content': 'passage text' }")),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingexammodel')),
            ],
        ),
    ]
