# Generated by Django 5.2.7 on 2025-11-14 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinganswermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingevaluationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingevaluationmodel',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='reading.readingexammodel'),
        ),
        migrations.AddField(
            model_name='readinganswermodel',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.readingexammodel'),
        ),
        migrations.AddField(
            model_name='readingpassagemodel',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingexammodel'),
        ),
        migrations.AddField(
            model_name='readinganswermodel',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.readingpassagemodel'),
        ),
        migrations.AddField(
            model_name='readingquestionmodel',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingpassagemodel'),
        ),
        migrations.AddField(
            model_name='readingoptionmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reading.readingquestionmodel'),
        ),
        migrations.AddField(
            model_name='readinganswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.readingquestionmodel'),
        ),
    ]
