# Generated by Django 5.2.7 on 2025-12-07 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_readingquestionrange_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFNGQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(unique=True)),
                ('statement', models.TextField()),
                ('correct_answer', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('not_given', 'Not Given')], max_length=10)),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingquestionrange')),
            ],
        ),
    ]
