# Generated by Django 5.2.7 on 2025-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='qualifion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
