# Generated by Django 5.2.7 on 2025-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_authors_qualifion'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='qualification',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
