# Generated by Django 5.2.7 on 2025-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_authors_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
    ]
